[workspace]

[package]
name = "crate_batch_3_fuzz_12228132628757202096"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "crate_batch_3_fuzz_12228132628757202096"
path = "src/crate_batch_3_fuzz_12228132628757202096.rs"

[dependencies]
afl = "=0.15.7"
home = "=0.5.9"
global_data = { path = "/root/deepSURF/code/global_data" }
crate_batch_3 = { path = "/workspace/crate_batch_3/" }