[workspace]

[package]
name = "crate_batch_5_fuzz_17713093821510439994"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "crate_batch_5_fuzz_17713093821510439994"
path = "src/crate_batch_5_fuzz_17713093821510439994.rs"

[dependencies]
afl = "=0.15.7"
home = "=0.5.9"
global_data = { path = "/workspace/deepSURF/code/global_data" }
crate_batch_5 = { path = "/workspace/crate_batch_5" }